DROP DATABASE IF EXISTS library;
CREATE DATABASE library;

USE library;

DROP TABLE IF EXISTS CSVImport;
CREATE TABLE CSVImport (
	ISBN   BIGINT  NULL,
	TITLE  VARCHAR(200) NOT NULL,
	NAME   VARCHAR(1000) NOT NULL
);

DROP TABLE IF EXISTS BORROWER;
CREATE TABLE BORROWER (
	Card_id   INT NOT NULL AUTO_INCREMENT,
	Ssn       CHAR(11),
	Bname     VARCHAR(50),
	Address   VARCHAR(100),
	Phone     VARCHAR(50),
	CONSTRAINT pk_BORROWER PRIMARY KEY (Card_id)
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
	Isbn      BIGINT NOT NULL,
	Title     VARCHAR(200) NOT NULL,
	Name      VARCHAR(2000),
	CONSTRAINT pk_BOOK PRIMARY KEY (Isbn)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
	Aid       INT NOT NULL AUTO_INCREMENT,
	Isbn      BIGINT NOT NULL,
	Name      VARCHAR(1000),
	CONSTRAINT pk_AUTHOR PRIMARY KEY (AID)
);

DROP TABLE IF EXISTS LOAN;
CREATE TABLE LOAN (
	L_id         INT NOT NULL AUTO_INCREMENT,   
	I_no         BIGINT,
	C_id         INT  DEFAULT 0,
	Date_out     VARCHAR(20),
	Due_date     VARCHAR(20),
	Date_in      VARCHAR(20),
	CONSTRAINT pk_BOOK_LOANS PRIMARY KEY (L_id)
);

DROP TABLE IF EXISTS FINES;
CREATE TABLE FINES (
	Loan_id   INT NOT NULL,
	Fine_amt  DECIMAL(6,2) DEFAULT 0.00,
	Paid      INT DEFAULT 0,
	CONSTRAINT fk_FINES FOREIGN KEY (Loan_id) references LOAN (L_id)
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT (
	Card_id    INT  NOT NULL,
	Amount     DECIMAL(6,2) DEFAULT 0.00,
	CONSTRAINT pk_PAYMENT PRIMARY KEY (Card_id)
);

LOAD DATA LOCAL INFILE 'C:/Users/Ying Yi/Desktop/db_project1/data.csv'
INTO TABLE CSVImport
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@col1, @col2, @col3)
set ISBN = @col1, TITLE = @col2, NAME = @col3;

LOAD DATA LOCAL INFILE 'C:/Users/Ying Yi/Desktop/db_project1/borrowers.csv'
INTO TABLE BORROWER
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@col1, @col2, @col3, @col4, @col5, @col6, @col7, @col8, @col9)
set Card_id = @col1, Ssn = @col2, Bname = CONCAT(@col3, ' ', @col4), Address = @col6, Phone = @col9;

INSERT INTO BOOK (Isbn, Title) 
SELECT DISTINCT ISBN, TITLE 
FROM CSVImport;

INSERT INTO LOAN (I_no)
SELECT Isbn
FROM BOOK;

INSERT INTO AUTHOR (ISBN, NAME) 
SELECT CSVImport.ISBN, CSVImport.NAME
FROM CSVImport;




